### PR TITLE
Add duplication check for test suites and test cases

### PR DESCRIPTION
**Pull request by literalEval**
Fixes: #217 

This PR enforces a check on Test Suite names and Test Case names so that no two Test Suites can have the same name, and the same for two test cases in the same suite. Also created the respective exception for both cases.

### CODE REVIEW

**Comment by literalEval** [comment]
@dakaa16 @Rune-Christensen please review. Thanks.

**Comment by dakaa16** [comment]
Hi @literalEval
Thank you for contributing. I will be able to thoroughly review your PR on monday. At a quick glance, it seems to be missing some unit tests.

**Comment by literalEval** [comment]
@dakaa16 Thanks. I'll add tests in the meantime.

**Comment by Rune-Christensen** [comment]
Hi @literalEval 

Please add some unit tests, to verify that the changes function as expected.
Thanks :-)

**Comment by Rune-Christensen** [comment]
Tests add through another pull request.
Thank you for contributing :-D

**Comment by literalEval** [comment]
@Rune-Christensen sure :)

**Pull request closed without merging**
